project:
  type: website
  output-dir: docs

website:
  title: "PURA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: updates.qmd
        text: Field Updates
      - href: publications.qmd
        text: Publications
      - href: photos.qmd
        text: Gallery
  page-footer: "© 2025 W. Christopher Carleton, Tho Thon, David Brotherson"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css



